// flow-typed signature: eeb2be8fcb612d0a790f16607fed91f7
// flow-typed version: <<STUB>>/react-resize-observer_v1.0.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-resize-observer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-resize-observer' {
  declare module.exports: any;
}
